apps/index/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:incorrect_data>', views.index, name='index'),
    path('auth/', views.auth, name='auth'),
    path('register/', views.register, name='register'),
    path('register/<int:unfortunately>', views.register, name='register'),
    path('register/new/<int:superuser>', views.new, name='new')
]

apps/lk/urls.py
from django.urls import path
from . import views

app_name = 'lk'
urlpatterns = [
    path('<str:user_login>', views.index, name="index"),
    path('<str:user_login>/history', views.view_history, name="view_history"),
    path('<str:user_login>/settings', views.settings, name="settings"),
    path('<str:user_login>/wait', views.wait, name="wait"),
    path('<str:user_login>/newPhoto', views.newPhoto, name="newPhoto"),
    path('<str:user_login>/newPhoto/<str:foodName>/<str:foodDescription>', views.chooseFood, name="chooseFood"),
    # path('<str:user_login>/upload_image', views.upload_image, name="upload_image"),
]

sova_avia/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.index.urls')),
    path('lk/', include('apps.lk.urls')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/index/models.py
from django.db import models


class User(models.Model):
    login = models.CharField(max_length=25, unique=True)
    password = models.CharField(max_length=25)
    email = models.CharField(max_length=35)
    phone = models.CharField(max_length=17)
    fio = models.CharField(max_length=100)

    def __str__(self):
        return self.login


class UserHistory(models.Model):
    userId = models.ForeignKey(User, on_delete=models.CASCADE)
    foodName = models.CharField(max_length=50)
    foodDescription = models.CharField(max_length=50)

apps/lk/models.py
from django.db import models


class Article(models.Model):
    file_obj = models.FileField(upload_to='media/')

apps/lk/forms.py
from django.forms import ModelForm
from .models import Article


class ArticleForm(ModelForm):
  class Meta:
    model = Article
    fields = ['file_obj']

apps/index/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import User


def index(request, incorrect_data=0):
    if incorrect_data:
        return render(request, 'index/incorrect.html')
    return render(request, 'index/index.html')


def register(request, unfortunately=None):
    if unfortunately is None:
        return render(request, 'index/register.html')
    if unfortunately:
        return render(request, 'index/incorrect_reg.html')
    return render(request, 'index/incorrect_password.html')


def auth(request):
    user_instance = User.objects.get(login=request.POST['login'])
    if user_instance.password == request.POST['password']:
        return HttpResponseRedirect(reverse('lk:index', args=(user_instance.login, )))
    else:
        return HttpResponseRedirect(reverse('index:index', args=(1, )))



def new(request):

    current_password = request.POST['password0u']
    if current_password == request.POST['password1u']:
        current_login = request.POST['loginu']
        for user in User.objects.all():
            if user.login == current_login:
                break
        else:
            User.objects.create(login=current_login, password=current_password)
            return HttpResponseRedirect(reverse('lk:index', args=(current_login, )))
        return HttpResponseRedirect(reverse('index:register', args=(1,)))
    else:
        return HttpResponseRedirect(reverse('index:register', args=(0,)))

apps/lk/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from apps.index.models import User, UserHistory
from sova_avia.settings import MEDIA_ROOT

from imageai.Prediction import ImagePrediction
import json

from .models import Article
from .forms import ArticleForm


def index(request, user_login):
    try:
        user = User.objects.get(login=user_login)
    except:
        raise Http404
    return render(request, 'lk/index.html', {'user_instance': user, 'user_login': user_login})


def view_history(request, user_login):
    # try:
    #     history = UserHistory.objects.get(userId = user_login)
    # except:
    #     raise Http404
    user_id = User.objects.get(login=user_login).id
    return render(request, 'lk/history.html', {'history': UserHistory.objects.all().filter(userId = user_id),
                                               'user_login': user_login})


def settings(request, user_login):
    try:
        user = User.objects.get(login=user_login)
    except:
        raise Http404
    return render(request, 'lk/settings.html', {'user_instance': user, 'user_login': user_login})


def wait(request, user_login):
    if request.POST['password0u'] == request.POST['password1u']:
        User.objects.get(login=user_login).password = request.POST['password0u']
        return HttpResponseRedirect(reverse('lk:index', args=(user_login,)))
    else:
        return render(request, 'lk/settings.html', {'user_instance': User.objects.get(login=user_login),
                                                    'user_login': user_login})


def newPhoto(request, user_login):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            file_name = request.FILES['file_obj']
            result = process_image(file_name)
            return render(request, 'lk/newPhoto.html', {'form': form, 'user_login': user_login, 'foodVariants': result})
            # return render(request, 'lk/newPhoto.html', {'form': request.POST, 'user_login': user_login})
    else:
        form = ArticleForm()

    return render(request, 'lk/newPhoto.html', {'form': form, 'user_login': user_login})
    # return render(request, 'lk/newPhoto.html', {'user_login': user_login})
    # return render(request, 'lk/newPhoto.html', {'user_login':user_login, 'foodVariants':
    # [{'foodName': 'котлетка', 'foodDescription': "мамина"}]})


def process_image(file_name):
    execution_path = "../../media/media/"

    with open(MEDIA_ROOT + '/media/' + 'foods.json') as f:
        foods = json.load(f)

    prediction = ImagePrediction()
    prediction.setModelTypeAsResNet()
    prediction.setModelPath(MEDIA_ROOT + "/media/resnet50_weights_tf_dim_ordering_tf_kernels.h5")
    prediction.loadModel()

    result = []

    predictions, probabilities = prediction.predictImage(MEDIA_ROOT + '/media/' + str(file_name), result_count=10)
    for eachPrediction, eachProbability in zip(predictions, probabilities):
        tmp = dict()
        eachPrediction = eachPrediction.replace('_', ' ')

        tmp['foodName'] = eachPrediction
        tmp['foodDescription'] = eachProbability
        calorieAmount = "124 cal"

        flag = False
        for food in foods:
            if food['foodName'] == eachPrediction:
                calorieAmount = food['foodDescription']
                flag = True
                break

        if flag:
            tmp['foodDescription'] = calorieAmount
            result.append(tmp)

    return result


def chooseFood(request, user_login, foodName, foodDescription):
    UserHistory.objects.create(userId=User.objects.get(login=user_login), foodName=foodName, foodDescription=foodDescription)
    return HttpResponseRedirect(reverse('lk:index', args=(user_login,)))

templates/admin_panel/topic_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Редактирование тем и вопросов</title>
</head>
<body>
<div class="card" style="justify-content: center">
  <div class="card-body">
    <form action="{% url 'index:auth' %}" method="POST">

        {% csrf_token %}

    <div class="login container">
        <div class="form-column row justify-content-center">
            <div class="col-6 col-md-4">
                <label for="#validationTooltip01">Topic Title</label>
            <input type="text" name="fio" class="form-control mb-2" id="validationTooltip01" placeholder="Topic title" required/>
                <label for="#validationTextarea">Topic text</label>
                <textarea class="form-control" id="validationTextarea" placeholder="Required example textarea" required></textarea>
                <button class="btn btn-outline-success btn-block mb-2 but" type="submit">Save changes</button>
            </div>
        </div>
    </div>
    </form>
      <form>
<div class="container">
                                <div class="row">
                        <h5 class="card-title col">course.title</h5>
                        <form ><button type="submit" class="btn btn-link col" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Редактировать курс</button>
                        <div class="collapse" id="collapseExample">
      <form>
          <input type="text" class="form-control" aria-label="Text input with radio button" required>
    <div class="input-group">
  <div class="input-group-prepend">
    <div class="input-group-text">
      <input type="radio" name="exampleRadios" id="exampleRadios1" value="option1" aria-label="Radio button for following text input" required>
    </div>
  </div>
  <input type="text" class="form-control" aria-label="Text input with radio button">
</div>

<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-outline-success">Сохранить изменения</button>
    </div>
    <div class="col">
        <form><button type="submit" class="btn btn-outline-info">ADD</button></form>
    </div>
</div>
    </form>
  </div>
</div></form>
                    </div>
                </div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/index/incorrect.html
{% extends 'index/index.html' %}

{% block incorrect_data %}
    <div class="alert alert-danger incorrect_data" role="alert">
        <p class="incorrect_data">Пароль или логин введены неправильно</p>
    </div>
{% endblock %}

templates/index/incorrect_password.html
{% extends 'index/register.html' %}

{% block incorrect_data %}
    <div class="alert alert-danger incorrect_data" role="alert">
        <p class="incorrect_data">Пароли не совпадают</p>
    </div>
{% endblock %}

templates/index/incorrect_reg.html
{% extends 'index/register.html' %}

{% block incorrect_data %}
    <div class="alert alert-danger incorrect_data" role="alert">
        <p class="incorrect_data">Такой логин уже занят</p>
    </div>
{% endblock %}

templates/index/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="../../media/static/css/main.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Вход в личный кабинет</title>
</head>
<body>
<form action="{% url 'index:auth' %}" method="POST">
    <header class="header">
        <div class="container">
            <div class="row header__inner">
                <div class="header__title">Войти</div>
            </div>
        </div>
    </header>

        {% csrf_token %}

    <div class="form">
        <div class="container">
            <div class="row form__inner">
                <div class="form__name">Имя</div>
                <input type="text" name="login" class="form__input login" id="validationTooltip01" placeholder="Логин" required/>

                <div class="form__name">Пароль</div>
                <input type="password" name="password" class="form__input password" id="validationTooltip02" placeholder="Пароль" required>
            </div>
            {% block incorrect_data %}{% endblock %}
        </div>
    </div>



    <div class="bttnNext">
        <div class="container">
            <div class="row reviewsBttn__inner">
                <a class="white__bttn" href="{% url 'index:register' %}">Зарегистрироваться</a>
                <button type="submit" href="#" class="reviews__button"><div class="reviews__bttnText">Далее</div></button>
            </div>
        </div>
    </div>

    </form>
</body>
</html>

templates/lk/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="../../media/static/css/main.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>История</title>
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="row header__inner">
                <a href="{% url "lk:index" user_login %}" class="header__back"><img src="../../media/static/img/header/Back%20Icon.svg" alt="back Icon"></a>
                <div class="header__title">История</div>
            </div>
        </div>
    </header>

    <div class="choice">
        <div class="container">
            <div class="row choice__inner">
            {% if history %}
                {% for food in history %}
                    <div class="white__bttn choice__bttn">
                        <span class="choice__title">{{ food.foodName }}</span>
                        <span class="choice__subtitle">{{ food.foodDescription }}</span>
                    </div>
                {% endfor %}
            {% else %}
                <div class="history">
                    <div class="row history__inner">
                        <div class="history__icon">
                            <img src="img/history/history__icon.svg" alt="icon">
                        </div>
                        <div class="history__title">Сделайте фотографию, <br> а мы сами поймем что ты ешь</div>
                    </div>
                </div>
            {% endif %}
            </div>
        </div>
    </div>
    {% if not  history %}
        <div class="bttnNext">
            <div class="container">
                <div class="row reviewsBttn__inner">
                    <a class="white__bttn history__bttn" href="{% url 'lk:index' user_login %}">Сделать фотографию</a>
                </div>
            </div>
        </div>
    {% endif %}
</body>
</html>

templates/lk/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="../../media/static/css/main.css">
    <link rel="stylesheet" href="../../media/static/fonts.css">


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ user_login }}</title>
</head>
<body>
{{ fileName }}
<main>
	<div class="container">
		<div class="row main__inner">
			<div class="main__title">Добро пожаловать, <br> {{ user_instance.login }}!</div>
		</div>
	</div>
</main>

<div class="makePhoto">
	<div class="container">
		<div class="row makePhoto__inner">
			<div class="col-12 makePhoto__title">Добавить новый продукт</div>
			<a href="{% url 'lk:newPhoto' user_login %}" class="makePhoto__button">
				<div class="makePhoto__buttonTitle">Сделай фотографию</div>
				<div class="makePhoto__buttonSubtitle">того, что ты ешь, а мы сами все поймем</div>
			</a>
		</div>
	</div>
</div>


<div class="journal">
	<div class="container">
		<div class="row">
			<div class="col-12 makePhoto__title">Журнал</div>
			<div class="col-6 journal__inner journal__left">
				<a href="{% url 'lk:view_history' user_login %}" class="journal__item">
					<div>
						<img src="../../media/static/img/main/historyAvatar.svg" alt="icon of this button" class="journal__icon">
					</div>
					<div class="journal__text">История</div>
					<div class="journal__subtext">Посмотри что ты ел</div>
				</a>
			</div>

			<div class="col-6 journal__inner journal__right disabled">
				<a class="journal__item">
					<div>
						<img src="../../media/static/img/main/goalAvatar.svg" alt="icon of this button" class="journal__icon">
					</div>
					<div class="journal__text">Цели</div>
					<div class="journal__subtext">Сделай себя лучше</div>
				</a>
			</div>

			<div class="col-6 journal__inner journal__left">
				<a href="{% url "lk:settings" user_login%}" class="journal__item">
					<div>
						<img src="../../media/static/img/main/settingsAvatar.svg" alt="icon of this button" class="journal__icon">
					</div>
					<div class="journal__text">Настройки</div>
					<div class="journal__subtext">Сделай все по себя</div>
				</a>
			</div>

			<div class="col-6 journal__inner journal__right disabled">
				<a class="journal__item">
					<div>
						<img src="../../media/static/img/main/feddbackAvatar.svg" alt="icon of this button" class="journal__icon">
					</div>
					<div class="journal__text">Обратная связь</div>
					<div class="journal__subtext">Сделай нас лучше</div>
				</a>
			</div>

		</div>
	</div>
</div>

{##}
{#    <div class="row container">#}
{#        <div class="col"><h5><strong>My profile</strong></h5></div>#}
{#        <div class="col-4"><h5>{{ user_instance.login }}</h5></div>#}
{#    </div>#}
{#    <div class="collapse show multi-collapse" id="multiCollapseExample1">#}
{#        <div class="card card-body container">#}
{#                <div class="row">#}
{#                <button id="switch" class="btn btn-link col" type="button" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Notifications</button>#}
{#            </div>#}
{#{#            <form action="" method="POST">#}
{##}
{#            {% csrf_token %}#}
{##}
{#            <div>#}
{#                <div class="form-column row justify-content-between">#}
{#                    <div class="col-8">#}
{#                    <label>ФИО</label>#}
{#                        <input type="text" name="fio" value="{{ user_instance.fio }}" class="form-control mb-2" id="validationTooltip01" placeholder="ФИО" required/>#}
{#                        <label>Город</label>#}
{#                        <input type="text" name="loginu" value="{{ user_instance.town }}" class="form-control mb-2" id="validationTooltip01" placeholder="Город" required/>#}
{#                        <label>Номер телеофна</label>#}
{#                        <input type="text" name="phone" value="{{ user_instance.phone }}" class="form-control mb-2" id="validationTooltip01" placeholder="Номер телеофна" required/>#}
{#                        <label>Опыт работы</label>#}
{#                        <input type="number" name="points" value="{{ user_instance.experience }}" class="form-control mb-2" id="validationTooltip01" step="1" placeholder="Опыт работы" required/>#}
{#                        <label>E-mail</label>#}
{#                        <input type="text" name="email" value="{{ user_instance.email }}" class="form-control mb-2" id="validationTooltip01" placeholder="E-mail" required/>#}
{#                        <label> Старый Пароль</label>#}
{#                        <input type="text" name="password0u" class="form-control mb-2" id="validationTooltip02" placeholder="Старый Пароль" required>#}
{#                    <label> Новый Пароль</label>#}
{#                        <input type="text" name="password0u" class="form-control mb-2" id="validationTooltip02" placeholder="Новый Пароль" required>#}
{#                        <label>Повторите новый пароль</label>#}
{#                        <input type="text" name="password1u" class="form-control mb-2" id="validationTooltip02" placeholder="Повторите новый пароль" required>#}
{#                        <label>Компания, где вы работаете</label>#}
{#                        <select name="title_company" class="custom-select" id="validationTooltip04" required>#}
{#                            {% if list_companies %}#}
{#                                {% for company in list_companies %}#}
{#                                    <option value="{{ company.id }}">{{ company.title_company }}</option>#}
{#                                {% endfor %}#}
{#                            {% else %}#}
{#                                <option selected value=":(">Ни одна компания не пользуется нашей платформой</option>#}
{#                            {% endif %}#}
{#                        </select>#}
{#                    <label>Специальность</label>#}
{#                        <select name="title_company" class="custom-select mb-3" id="validationTooltip04" required>#}
{#                            {% if list_spec %}#}
{#                                {% for spec in list_spec %}#}
{#                                    <option value="{{ spec.id }}">{{ spec.title }}</option>#}
{#                                {% endfor %}#}
{#                            {% else %}#}
{#                                <option selected value=":(">Специальностей нет</option>#}
{#                            {% endif %}#}
{#                        </select>#}
{#                        <button class="btn btn-outline-success btn-block mb-2" type="submit">Сохранить изменения</button>#}
{#                    </div>#}
{#                <div class="col justify-content-end">#}
{#                    <div class="column">#}
{#                    <div class="col"><img class="img-fluid" src="{{ MEDIA_URL }}{{ ex_image0.image.url }}" alt=""></div>#}
{#                    <div class="col"><img class="img-fluid" src="{{ MEDIA_URL }}{{ ex_image1.image.url }}" alt=""></div>#}
{##}
{#                    </div>#}
{#                </div>#}
{#                </div>#}
{#            </div>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#    <div class="collapse multi-collapse" id="multiCollapseExample2">#}
{#        <div class="card card-body container">#}
{#            <div class="row" style="justify-items: stretch">#}
{#                <button  id="switch" class="btn btn-link col" type="button" data-toggle="collapse" data-target=".multi-collapse" aria-expanded="false" aria-controls="multiCollapseExample1 multiCollapseExample2">Edit profile</button>#}
{#            </div>#}
{#    <div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">#}
{#      <div class="toast-header">#}
{#        <strong class="mr-auto">Стандартное уведомление</strong>#}
{#        <small class="text-muted">-20 seconds ago</small>#}
{#        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">#}
{#          <span aria-hidden="true">&times;</span>#}
{#        </button>#}
{#      </div>#}
{#      <div class="toast-body">#}
{#        Добро пожаловать к нам в команду#}
{#      </div>#}
{#    </div>#}
{#        </div>#}
{#    </div>#}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/lk/newPhoto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="../../media/static/css/main.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Новое фото</title>
</head>
<body>

{% if not foodVariants %}
    <form action="{% url 'lk:newPhoto' user_login %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <header class="header">
            <div class="container">
                <div class="row header__inner">
                    <a href="{% url 'lk:index' user_login %}" class="header__back">
                      <img src="../../media/static/img/header/Back%20Icon.svg" alt="back Icon">
                    </a>
                    <div class="header__title">Добавление продукта</div>
                </div>
            </div>
        </header>
      {{ form }}

{#       <div class="container">#}
{#           <div class="row addPhoto__inner">#}
{#               <div class="addPhoto__title">Добавить фотографию</div>#}
{#               <div class="form__inputPhoto">#}
{#                   <input required type="file" name="file" id="file" class="inputfile">#}
{#                   <label class="form__photo" for="file"><span>Добавить фотографию</span></label>#}
{#               </div>#}
{#           </div>#}
{#       </div>#}

        <div class="bttnNext">
            <div class="container">
                <div class="row reviewsBttn__inner">
                    <button type="submit" class="reviews__button">
                      <div class="reviews__bttnText">Далее</div>
                    </button>
                </div>
            </div>
        </div>
    </form>
{% else %}
    <form action="{% url 'lk:newPhoto' user_login %}" method="post">
    {% csrf_token %}
    <div class="choice">
        <div class="container">
            <div class="row choice__inner">
                {% for food in foodVariants %}
                    <a class="white__bttn choice__bttn" href="{% url 'lk:chooseFood' user_login food.foodName food.foodDescription %}">
                        <span class="choice__title">{{ food.foodName }}</span>
                        <span class="choice__subtitle">{{ food.foodDescription }}</span>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="bttnNext">
        <div class="container">
            <div class="row reviewsBttn__inner">
                <button type="submit" class="reviews__button"><div class="reviews__bttnText">Мы не угадали?</div></button>
            </div>
        </div>
    </div>
    </form>
{% endif %}
</body>
</html>

templates/lk/settings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="../../media/static/css/main.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Настройки</title>
</head>
<body>
<form action="{% url 'lk:wait' user_login %}" method="POST">
    {% csrf_token %}

    <header class="header">
        <div class="container">
            <div class="row header__inner">
                <a href="{% url 'lk:index' user_login %}" class="header__back"><img src="../../media/static/img/header/Back%20Icon.svg" alt="back Icon"></a>
                <div class="header__title">Настройки</div>
            </div>
        </div>
    </header>

    <div class="reviews">
        <div class="container">
            <div class="row reviews__inner">
                <label class="reviews__title"> Новый Пароль</label>
                <input type="text" name="password0u" class="form__input password" id="validationTooltip02" placeholder="Старый Пароль" required>
                <label class="reviews__title">Повторите новый пароль</label>
                <input type="text" name="password1u" class="form__input passwordReset" id="validationTooltip02" placeholder="Новый Пароль" required>

            </div>
        </div>
    </div>

    <div class="bttnNext">
        <div class="container">
            <div class="row reviewsBttn__inner">
                <button type="submit" class="reviews__button"><div class="reviews__bttnText">Применить</div></button>
            </div>
        </div>
    </div>

</form>
</body>
</html>